apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:8lXJN5vdmhGBmoxgbQB4AeQhVBn9xS9OnH81zWyOJ0w6qes7OuqbGw==,iv:5b26Q/WQefA7cyVs1BSfFVdsmtigmrF5TaBWybFruiI=,tag:Jd+eLp8/MzGLNTdX/+jesA==,type:str]
sops:
  age:
    - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOStqSXpQVTQ2bDFkSERV
        Q2xpbEpLYTFkc3o4bVYxQy91VlVpRlNBWXdnCjA5ZUpHcDFhbzB4SUhlc2ZJcm9K
        c2hNb2FRSlFmcS81cXFyTllkWnl0WlkKLS0tIHNkOWdXeWY2WGFMUmdJdTV4MGdW
        N0JLcFViT3J4NG9xYW14aUluR0hsVzQK6EcJD/wLijUKnKjR6k+WslLP02/MnZI/
        DR3YS8vSKGj4ZjsXu2whyBkoM6EqlmY4gYExxSrALrq02ix9EmtLGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:29:57Z"
  mac: ENC[AES256_GCM,data:dWgGaMCWsB7lxCEOB2WGijFLu260UOoS7EN5IyWvGOM3Lp0jlTB84UQ+sVtHUr5nMDqOfehWRSG23pNfvuO9onUyqBI4riNqvLuMoJpekiNZ2Cz1k+dTeMmTDFkbPGwRIU3GvoCwt2zBEJCJY6MDU2B16EsMBdyzbqokUZ41IN4=,iv:ZwwVeX/tB9Bf22lrcRUHRfdcsnnRDjxESLfkycf3kwk=,tag:KAnOuLjXoztVMppMevLZSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
