apiVersion: v1
kind: Secret
metadata:
    name: odoo-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:etSb+A==,iv:Aksk1nH+xtmqrj9Qv8eg2czJtzI4KNULFMVJ/2FS5HU=,tag:4dmhR1QlzoLfSMc0qJHyxA==,type:comment]
    DB_NAME: ENC[AES256_GCM,data:RkbLdQ==,iv:klWyWd2T9ulh3um912iEKutMkd5QurHZxt9nCnEvKrw=,tag:trT/3vIgwQ4epamTdiKSQg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:qHdb8FH4s7YqGNQx+7suICJlAnuFNhVo3+ojXUnS5XzFvUpiCmts9g==,iv:bNxT3B7HOsNQZGGfI1NbXT+CUDXryEYtHNFUy5WULdI=,tag:bxwbQ4H8wmMxdlEwq2+l5w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:M7CoHQ==,iv:vzaChA8quVoh4KW+hqC1d/0dL7XRaoHbdR9Mgdlw4lk=,tag:9g4/jyauKsXZuvwBu0TGQA==,type:str]
    DB_USER: ENC[AES256_GCM,data:I3MPyuLvzjL86Q==,iv:gyEzOAyDyNA4xze2smG1P2sxRIMGTi4rcK2JoHUiH60=,tag:BcTstkYqgPmmnWjflRJWSA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rw/DPorxSez6WHEiNy4C9T91ojuyw5I3KrZcpGy966g=,iv:UH/ho0vHKkyh4/bvKF7xsyBBpvkM9yQbot8RXH+iHms=,tag:/P6XalWRK5wGWm8vZbs1BQ==,type:str]
sops:
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdMOFlqaXRNL213WVdH
            cUwxbG9yaWRNSWE1M0ptcFdWeUg4TUhhRUE0CnM4TkdpUEs4ek1LTVNiS0lWT3Zx
            ald1L2V4Vk8xdkh1aDNCZUNIZVQvak0KLS0tIERGR25JVHhqcDkyQlgwWjJ4ckhr
            NnlsUGVsdk95eDU2YnFJSVJHbkZNVlkK1ui5f0PblFAFDqMfy0Dd3QNcl8uj4rTq
            qvbPDb/hBw1xX7znZEi2VV2GTLzQ93NLIjodUW7+F1EnW+1CnZu05g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T15:03:10Z"
    mac: ENC[AES256_GCM,data:fOFf2EQI13JsHewi5++tm2VtF+bEp8ugv17LOU9aC+bszkpY3/y4Hd0KDVct/UAihtABwHZUCHjal1czeZTQaS1XCMIpnSTlXrRmh/HbNGayPG9sJpkNEznNmzdTVL7nnv4MVcI3Tx6LVJ66rzf/7/o1lQKLJhW4ZCXIunoi7pg=,iv:XwlkhT3RAqxTO7zV5bT/brOy9a2MQxAHU3Wjc1akp6E=,tag:hS1K9cEBOLaxpBcNQx8vxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: odoo-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:0szkl/G/PPM=,iv:Ga/DQgfpnE6XGsMFSIYKBH243yhNHFKX+vWrnjBaDDs=,tag:rVUa8+zWyyTLdEa7YHvxXA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xvHptniXdxwT0IVn6s9N2PNtKFD20gYqYmdA5h16H7X7dFU639i5icaZjyUtU2IWy1BAV80gtQk=,iv:2LbEJ1ykODtgB+1hzd4qhY2DHCiIpcfg0H9J0FNtwpI=,tag:agDLPRdnV+173FNWik0ZuQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:FzTQCCNeluAb7hTk2qBMWw==,iv:hm0vlaI9nTVSoWjxhjw1tbl7dtkGTLmspfA0ZOKEsVo=,tag:8CUlLzr52BHMfQa+MD3zuA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Rr09t41qOYCkcUBw2ZCEKoLF5i1GrJgk/rO7rof0L0nPc9q8+ROFPE7CeBU=,iv:rT9sYo5ncTr5s6XS4v5GwS1FK0Yrp7GsmIlMr68Mx3k=,tag:AwQZczzeU0CPlXsDUlKX6g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:l5ZM/0n3DWBbKJtNHvrB2kEBS+Pqgvvwtg==,iv:oFvaZ79/Yy7/zsodljROZgGE5Ur56o3Ww/diHkgYlT0=,tag:Oy8SKKNdCMF6moh47fnRBA==,type:str]
sops:
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdMOFlqaXRNL213WVdH
            cUwxbG9yaWRNSWE1M0ptcFdWeUg4TUhhRUE0CnM4TkdpUEs4ek1LTVNiS0lWT3Zx
            ald1L2V4Vk8xdkh1aDNCZUNIZVQvak0KLS0tIERGR25JVHhqcDkyQlgwWjJ4ckhr
            NnlsUGVsdk95eDU2YnFJSVJHbkZNVlkK1ui5f0PblFAFDqMfy0Dd3QNcl8uj4rTq
            qvbPDb/hBw1xX7znZEi2VV2GTLzQ93NLIjodUW7+F1EnW+1CnZu05g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T15:03:10Z"
    mac: ENC[AES256_GCM,data:fOFf2EQI13JsHewi5++tm2VtF+bEp8ugv17LOU9aC+bszkpY3/y4Hd0KDVct/UAihtABwHZUCHjal1czeZTQaS1XCMIpnSTlXrRmh/HbNGayPG9sJpkNEznNmzdTVL7nnv4MVcI3Tx6LVJ66rzf/7/o1lQKLJhW4ZCXIunoi7pg=,iv:XwlkhT3RAqxTO7zV5bT/brOy9a2MQxAHU3Wjc1akp6E=,tag:hS1K9cEBOLaxpBcNQx8vxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0