apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PRr2aq3ydXzGlg==,iv:ZtjeWiestPlUcWbTbgLYNkPS7mHgdwp+6TupoG+5CyQ=,tag:krVFGvDIwJ1ljD5QTOQxoQ==,type:str]
sops:
  age:
    - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDMvOUVFVEQ5R1VkcHN4
        dWplU0cvRldlN29KU0Jub0h4UDFUVEZhQ1hRCk85L2hMRXZianRNRHR0NlJ0eW9P
        MkFLdzdqbzZjb2hIaVlFTysyN1RJSE0KLS0tIGtRc0FZemwzZlhpdVpTcnNBeGVr
        Y2krb0pVTWk0TnJLalhhT09pZC82bXMKW59BVpnSVACGbzVgJtdOAjW9qVOTTjpW
        RLuyt+Nct7O+eYb2ZenB8aohSsanVzmU4mFvh3yKaKEFnMPhcCXmjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:29:57Z"
  mac: ENC[AES256_GCM,data:3X/B8ZQ4OMBhsy8Jatrk94yxAbmRZY5udNI2K6jqq80vn1COis9GFR4/3ZqRFCn1wLnNNqsF7zwA4Q7D705D7rrdFvvzJwP34mTowhnXPmCYmCtfG+flYpyFfRbfDar0JV6H42qAjg0qKwzXw1djanJWcuI15H50aSWH4ppK7ds=,iv:nqf9TOD2It2pc924G1XFlXG3QZFIkz6Nx2keH/iLsEY=,tag:XGXhocwYYJoXYpgVjq7/aQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
