apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CEivAqWvr7B/yaalRXwv/W6Nc5fXEQKEADLFuazrPBQ=,iv:tBZYnDVWNHeiqFnG0Oi87bHFNPwrpreWt5Hp0xes9HM=,tag:3AsHn+D0y34MsTLhxrjl4w==,type:str]
sops:
  age:
    - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFhUVzRBY3hGS3h0QzZW
        alZuRHEyZmphZ0NKSHo3R1ZSUkpBU1Z3YjBjCnBibkM0cExQWFVtQzVMeko1Vngv
        L2ROK1NvdzRuVDhQTXZlbW5lckxuOGcKLS0tIHFvZ25ndExHbGF1SVZ2K2cvd2M5
        TkNycWFsNWJSa0l5ZGltekdxcksxY0kK33VqgFLQO/IuT5Qz7fsPN3L6w238VpqV
        CUgGruBCWFDoAP1olU8e/K74iKDlvSR0FTDwGYNf5Fiu3zjoYsGD2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:29:57Z"
  mac: ENC[AES256_GCM,data:bSB0VC3AjQbGhJybKPhJRgQl7kDOAhj6x+92vhFRib4svEr5OemLe94XGCapaHpeZixZ+Fio0dKwfTfcUVIZus+P1dRVH8ogBbOepCQfseJzKWy7N9H0Ai5ia4g2pCbTFCk7sOpoiEh/3UvUy8lEfFeLBIiWYgnS8bWdLGK3u8Q=,iv:fa605XbzuUCQB8o0R7SDr9f8wTdo67tBOFGEZ0cOHcI=,tag:y+dNwmG/kzVr2ZAZWPn1cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
