apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nHTET/Et4LQFEMPzh0J5dcNV8oMrDEN1Cz795EgI7lf24FtmLbaKeA==,iv:i40et4xvqFptw0xfd6CBKWRexd+7mZtYeErIcpNG2Ig=,tag:1C5z+Qad9npkVNrdaV+99Q==,type:str]
sops:
  age:
    - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
        MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
        Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
        SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
        gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:29:57Z"
  mac: ENC[AES256_GCM,data:dVfkgnzCkBVMOb0kQDmthZhznZF1EXr4bsCD61xmYETAqemhia1LWT8dl1TsGoNhs0hzSWLKh2IcO2ITVGe0c96ykO/QWZLtHjUZ2FcNyiwnZghW8M9l+xgEH17js1pStnqHrKQMDI42rsopV5aDt29rcQSSmMxeazl1obAEVsU=,iv:Ua8hBzwKeVLiW0FHb1k/VNxwNiv04EliXVnVIF+IUQ4=,tag:wtvNxLu/Dw8qd+sZXt1euA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
