apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ZIe7PD178e7sRP3JvxaJF79x6O/Xr3zjf93uH0wqEkVyAL4HaV9vU+kePQozGmzFe7b0olUy0j7byxi9VvHQcQH7smgorPIIXRgL/al4FOG+sE5pCSBi2gI/IDqzml1h1QTSp70bDAlWAW/6Fwzym+/yYPmUHkhuT059VHM5z14iRWtU7sUeAqViwipp/62zQH2gpU116H+U2V3K5iq2mb0828jovcVXc+nRwpG6A5yZySbY,iv:mCj/AKV36YRZlL/bgJgG/3vMCnmt4HXghJPFWDVvpAo=,tag:4LQW4E6yEq1/5QEgYBQIaA==,type:str]
sops:
  age:
    - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWFZGdk0rVTlSNU0xL0pk
        N2R2Zm44azhtKzhwaGU5WC93bCtPVXJXaFNjCjI0Y2Npa3FueUdsVCsrQm5uWXFG
        TDlLdlpneVl5MXM2RzJwSFQrc0dQY3cKLS0tICtpRDdSMTRTbVNLTXlCd1F2endt
        aklHMDMrNkJ5UlhQVncxNXVDci9QUzQKgWrjO4jRcVJka6Y6XJFenUOhWXEH8YE+
        5f85n6o3O51+8+Wk+QhbGPHjoT27vC+TUCo2UIa2u8OWGWgjjtXZJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:29:57Z"
  mac: ENC[AES256_GCM,data:S8ElaXdTQOFKKOfoM3GSDUaUSJbqzBsqE9kvXsVYLlPq4Vwhbe6SgE+K33wiY71Qs5Vu8G5roDPHlqcJTT5NuiVFJmIj5zSVqaMQICdW/9GWca80Wl0vzLe3J7xhIvhsW6deUfP1DXK5hn9D+egYPcnHHeqwUAUo0RHyie5+KCg=,iv:FlJB3MYJZNQ8r25kOyD0iE952E+R0FrcJNgS5dcGvdo=,tag:CRnYuyTjPmb1kgtrcIbYkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
